[2024-11-15T20:42:39.024+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T20:42:39.202+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T20:41:59.099792+00:00 [queued]>
[2024-11-15T20:42:39.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T20:41:59.099792+00:00 [queued]>
[2024-11-15T20:42:39.404+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-15T20:42:39.542+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingest_to_postgres> on 2024-11-15 20:41:59.099792+00:00
[2024-11-15T20:42:39.569+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=559) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T20:42:39.577+0000] {standard_task_runner.py:63} INFO - Started process 561 to run task
[2024-11-15T20:42:39.579+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FLOAT_DATA_TO_PG', 'ingest_to_postgres', 'manual__2024-11-15T20:41:59.099792+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_float_data.py', '--cfg-path', '/tmp/tmpexunyvhg']
[2024-11-15T20:42:39.592+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask ingest_to_postgres
[2024-11-15T20:42:40.045+0000] {task_command.py:426} INFO - Running <TaskInstance: FLOAT_DATA_TO_PG.ingest_to_postgres manual__2024-11-15T20:41:59.099792+00:00 [running]> on host 35eb7317174e
[2024-11-15T20:42:40.554+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='FLOAT_DATA_TO_PG' AIRFLOW_CTX_TASK_ID='ingest_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T20:41:59.099792+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T20:41:59.099792+00:00'
[2024-11-15T20:42:40.560+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T20:42:40.910+0000] {logging_mixin.py:188} INFO - Connecting to PostgreSQL at host.docker.internal:5432 with user admin
[2024-11-15T20:42:41.370+0000] {logging_mixin.py:188} INFO - Transformed data successfully ingested into PostgreSQL using pandas
[2024-11-15T20:42:41.371+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-15T20:42:41.376+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T20:42:41.441+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=FLOAT_DATA_TO_PG, task_id=ingest_to_postgres, run_id=manual__2024-11-15T20:41:59.099792+00:00, execution_date=20241115T204159, start_date=20241115T204239, end_date=20241115T204241
[2024-11-15T20:42:41.626+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-15T20:42:41.775+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T20:42:41.785+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
