[2024-11-15T22:18:43.412+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T22:18:43.523+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CLICKUP_DATA_TO_PG.transform_data manual__2024-11-15T22:18:28.865315+00:00 [queued]>
[2024-11-15T22:18:43.562+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CLICKUP_DATA_TO_PG.transform_data manual__2024-11-15T22:18:28.865315+00:00 [queued]>
[2024-11-15T22:18:43.563+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-15T22:18:44.055+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-11-15 22:18:28.865315+00:00
[2024-11-15T22:18:44.088+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1619) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T22:18:44.095+0000] {standard_task_runner.py:63} INFO - Started process 1621 to run task
[2024-11-15T22:18:44.096+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'CLICKUP_DATA_TO_PG', 'transform_data', 'manual__2024-11-15T22:18:28.865315+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/etl_process_clickup_data.py', '--cfg-path', '/tmp/tmpsvzsvox0']
[2024-11-15T22:18:44.112+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask transform_data
[2024-11-15T22:18:44.282+0000] {task_command.py:426} INFO - Running <TaskInstance: CLICKUP_DATA_TO_PG.transform_data manual__2024-11-15T22:18:28.865315+00:00 [running]> on host 35eb7317174e
[2024-11-15T22:18:44.609+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='CLICKUP_DATA_TO_PG' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T22:18:28.865315+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T22:18:28.865315+00:00'
[2024-11-15T22:18:44.612+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T22:18:44.755+0000] {etl_process_clickup_data.py:57} INFO - Transformed DataFrame:
[2024-11-15T22:18:44.756+0000] {etl_process_clickup_data.py:61} ERROR - An error occured: name 'df_transformed' is not defined
[2024-11-15T22:18:44.758+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-15T22:18:44.759+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T22:18:44.783+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=CLICKUP_DATA_TO_PG, task_id=transform_data, run_id=manual__2024-11-15T22:18:28.865315+00:00, execution_date=20241115T221828, start_date=20241115T221843, end_date=20241115T221844
[2024-11-15T22:18:44.851+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-15T22:18:44.902+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-15T22:18:44.906+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
